version: 0.0
os: linux

files:
  - source: frontend/dist
    destination: /var/www/my-angular-project

  - source: backend/build/libs
    destination: /opt/app

permissions:
  - object: /var/www/my-angular-project
    pattern: '**'
    mode: '0755'
    owner: www-data
    group: www-data
    type:
      - file
      - directory

hooks:
  BeforeInstall:
    - location: deploy-scripts/before-install.sh
      timeout: 60
      runas: root
  
  ApplicationStart:
    - location: deploy-scripts/application-start-hook.sh
      timeout: 300
      runas: root
  
  ApplicationStop:
    - location: deploy-scripts/application-end-hook.sh
      timeout: 300
      runas: root
