version: 0.2


phases:
  install:
    runtime-versions:
      java: corretto17
      nodejs: 18
    commands:
      - echo "Installing dependencies..."

  pre_build:
    commands:
      - echo "Frontend install"
      - cd frontend
      - npm ci
      - cd ..

  build:
    commands:
      - echo "Frontend build"
      - cd frontend
      - npm run build
      - cd ..

      - echo "Backend build"
      - cd backend
      - chmod +x gradlew
      - ./gradlew clean build -x test
      - cd ..

  post_build:
    commands:
      - echo "Build completed at $(date)"

artifacts:
  files:
    - appspec.yml
    - 'deploy-scripts/**/*'
    - backend/build/libs/*.jar
    - 'frontend/dist/**/*'
  discard-paths: no
