version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
      nodejs: 18

  pre_build:
    commands:
      - echo "Frontend install"
      - cd frontend
      - npm ci
      - cd ..

  build:
    commands:
      - echo "Frontend build"
      - cd frontend
      - npm run build
      - cd ..

      - echo "Backend build"
      - cd backend
      - chmod +x gradlew
      - ./gradlew clean build -x test
      - cd ..

  post_build:
    commands:
      - echo "=== root ==="
      - pwd
      - ls -al

      - echo "=== backend ==="
      - ls -al backend/build/libs || true

      - echo "=== frontend ==="
      - ls -al frontend/dist || true

      - zip -r deploy.zip appspec.yml deploy-scripts backend/build/libs frontend/dist
      - unzip -l deploy.zip


artifacts:
  files:
    - deploy.zip
