version: 0.2


phases:
  install:
    runtime-versions:
      java: corretto17
      nodejs: 18
    commands:
      - echo "Installing dependencies..."

  pre_build:
    commands:
      - echo "Frontend install"
      - cd frontend
      - npm ci
      - cd ..

  build:
    commands:
      - ng test --no-watch --no-progress --browsers=ChromeHeadLessCI

  post_build:
    commands:
      - echo "Test completed at $(date)"
